name: build & publish Docker image
on:
  push:
    branches:
      - main
jobs:
  lint-test:
    name: lint & test
    uses: './.github/workflows/test.yml'

  build-and-publish:
    name: build & publish Docker image
    needs: [lint-test]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: configure Docker to use buildx
        uses: docker/setup-buildx-action@v3
      - name: log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: determine image tag
        id: img-tag
        run: echo "::set-output name=tag::$(date -u +'%Y-%m-%dT%H.%M.%SZ')"

      - name: push Docker image to GitHub Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{github.repository}}:latest
            ghcr.io/${{github.repository}}:${{steps.img-tag.outputs.tag}}
          # https://docs.docker.com/build/ci/github-actions/examples/#github-cache
          cache-from: type=gha
          cache-to: type=gha,mode=max,oci-mediatypes=true,compression=zstd
